spring:
  application:
    name: "salaoApiOficial"
  datasource:
    url: "jdbc:postgresql://localhost:5432/Teste"
    username: "postgres"
    password: "postgres"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: true  # Mostra os comandos SQL no console
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update