#spring:
#  application:
#    name: "doRio"
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/Teste"
#    username: "postgres"
#    password: "postgres"
#    driver-class-name: "org.postgresql.Driver"
#  jpa:
#    show-sql: true # Mostra os comandos SQL no console
#    properties:
#      hibernate:
#        dialect: "org.hibernate.dialect.PostgreSQLDialect"
#    hibernate:
#      ddl-auto: update

spring:
  application:
    name: "doRio"
  datasource:
    url: "jdbc:postgresql://localhost:5432/Teste"
    username: "postgres"
    password: "postgres"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: WARN
    javafx: ERROR
    org.hibernate: WARN
    org.springframework: WARN
